// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"service/pkg/api"
	"service/pkg/api/service"
	"service/pkg/config"
	"service/pkg/db"
	"service/pkg/repo"
)

// Injectors from wire.go:

func InitializeServer(c *config.Config) (*api.Server, error) {
	gormDB, err := db.InitDb(c)
	if err != nil {
		return nil, err
	}
	userRepo := repo.NewUserRepo(gormDB)
	authServiceServer := service.NewUserServer(userRepo)
	server, err := api.NewGrpcServe(c, authServiceServer)
	if err != nil {
		return nil, err
	}
	return server, nil
}
